name: animal_search_front
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.8
  image_picker: ^0.8.4+4
  flutter_svg: ^1.1.6
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.5
  permission_handler: ^11.0.1
  firebase_auth: ^4.16.0
  firebase_app_check: ^0.2.2 # ✅ Adicionada esta linha
  path: ^1.9.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/animal.svg
    - assets/icons/plus.svg
    - assets/icons/AnimalSearch.png
    - assets/icons/google.png
